# Generated by Django 3.2.3 on 2021-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(default='Non definie')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('type', models.CharField(choices=[('fr', 'Frais'), ('cs', 'Conserve'), ('em', 'emballe')], default='em', max_length=2)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
