# Generated by Django 3.2.3 on 2021-05-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_commande_emballage_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='emballage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.emballage'),
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.fournisseur'),
        ),
    ]
